// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwbkdjmmwmpnxjeuzogo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3Ymtkam1td21wbnhqZXV6b2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTA3NDUsImV4cCI6MjA3MjQ4Njc0NX0.BUGFv4V7xSnkSEoioa39w4rANH2pl4UACkCvBWpNk3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});